#!/usr/bin/env bash

normal=$'\e[00m'
reset=$'\e[39m'

black=$'\e[0;30m'
red=$'\e[0;31m'
green=$'\e[0;32m'
yellow=$'\e[0;33m'
orange="\e[0;33m";
blue=$'\e[0;34m'
purple=$'\e[0;35m'
violet="\e[0;35m";
cyan=$'\e[0;36m'
white=$'\e[0;37m'

bold_black=$'\e[1;30m'
bold_red=$'\e[1;31m'
bold_green=$'\e[1;32m'
bold_yellow=$'\e[1;33m'
bold_orange="\e[1;33m";
bold_blue=$'\e[1;34m'
bold_purple=$'\e[1;35m'
bold_violet="\e[1;35m";
bold_cyan=$'\e[1;36m'
bold_white=$'\e[1;37m'

underline_black=$'\e[4;30m'
underline_red=$'\e[4;31m'
underline_green=$'\e[4;32m'
underline_yellow=$'\e[4;33m'
underline_orange=$'\e[4;33m'
underline_blue=$'\e[4;34m'
underline_purple=$'\e[4;35m'
underline_violet=$'\e[4;35m'
underline_cyan=$'\e[4;36m'
underline_white=$'\e[4;37m'

background_black=$'\e[40m'
background_red=$'\e[41m'
background_green=$'\e[42m'
background_yellow=$'\e[43m'
background_orange=$'\e[43m'
background_blue=$'\e[44m'
background_purple=$'\e[45m'
background_violet=$'\e[45m'
background_cyan=$'\e[46m'
background_white=$'\e[47m'

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors

    bold=$(tput bold)
    reset=$(tput sgr0) || $reset
    black=$(tput setaf 0) || $black

    # Solarized colors, taken from http://git.io/solarized-colors.
    blue=$(tput setaf 33) || $blue
    cyan=$(tput setaf 37) || $cyan
    green=$(tput setaf 64) || $green
    orange=$(tput setaf 166) || $yellow
    purple=$(tput setaf 125) || $purple
    red=$(tput setaf 124) || $red
    violet=$(tput setaf 61) || $purple
    yellow=$(tput setaf 136) || $yellow
    white=$(tput setaf 15) || $white
fi;
