#!/usr/bin/env bash

if [[ -f "colors" ]]; then
    source colors
fi

# Create a new directory and enter it
function mkd() {
    mkdir -p "$@" && cd "$_";
}

# Open Google Chrome with the specified URL, with no chrome
function chrome() {
    open -n -a "Google Chrome" --args "--app=${1}";
}

# Change working directory to the top-most Finder window location
function cdf() { # short for `cdfinder`
    cd "$(osascript -e 'tell app "Finder" to POSIX path of (insertion location as alias)')";
}

# Use Git’s colored diff when available
hash git &>/dev/null;
if [ $? -eq 0 ]; then
    function diff() {
        git diff --no-index --color-words "$@";
    }
fi;

# Create a data URL from a file
function dataurl() {
    local mimeType=$(file -b --mime-type "$1");
    if [[ $mimeType == text/* ]]; then
        mimeType="${mimeType};charset=utf-8";
    fi
    echo "data:${mimeType};base64,$(openssl base64 -in "$1" | tr -d '\n')";
}

# Create a git.io short URL
function gitio() {
    if [ -z "${1}" -o -z "${2}" ]; then
        echo "Usage: \`gitio slug url\`";
        return 1;
    fi;
    curl -i https://git.io/ -F "url=${2}" -F "code=${1}";
}

# Syntax-highlight JSON strings or files
# Usage: `json '{"foo":42}'` or `echo '{"foo":42}' | json`
function json() {
    if [ -t 0 ]; then # argument
        python -mjson.tool <<< "$*" | pygmentize -l javascript;
    else # pipe
        python -mjson.tool | pygmentize -l javascript;
    fi;
}

# UTF-8-encode a string of Unicode symbols
function escape() {
    printf "\\\x%s" $(printf "$@" | xxd -p -c1 -u);
    # print a newline unless we’re piping the output to another program
    if [ -t 1 ]; then
        echo ""; # newline
    fi;
}

# `s` with no arguments opens the current directory in Sublime Text, otherwise
# opens the given location
function s() {
    if [ $# -eq 0 ]; then
        subl .;
    else
        subl "$@";
    fi;
}

# `a` with no arguments opens the current directory in Atom Editor, otherwise
# opens the given location
function a() {
    if [ $# -eq 0 ]; then
        atom .;
    else
        atom "$@";
    fi;
}

# `v` with no arguments opens the current directory in Vim, otherwise opens the
# given location
function v() {
    if [ $# -eq 0 ]; then
        vim .;
    else
        vim "$@";
    fi;
}

# `o` with no arguments opens the current directory, otherwise opens the given
# location
function o() {
    if [ $# -eq 0 ]; then
        open .;
    else
        open "$@";
    fi;
}

function aka() {
    if [ $# -eq 0 ]; then
        alias;
    else
        alias | grep $@ --color=auto;
    fi;
}

# `tre` is a shorthand for `tree` with hidden files and color enabled, ignoring
# the `.git` directory, listing directories first. The output gets piped into
# `less` with options to preserve color and line numbers, unless the output is
# small enough for one screen.
function tre() {
    local levels=${1:-3}; shift
    tree -aC -I '.git|node_modules|bower_components|.DS_Store|storage' --dirsfirst -L $levels "$@" | less -FRNX;
}

function fixlocaldatabase() {
    echo "Delete the offending line from ~/.ssh/known_hosts. Opening in Sublime Text... Press [Enter] when ready."
    read
    subl ~/.ssh/known_hosts
}

function command_success {
  [[ $? -eq 0 ]]
}

function command_fail {
  [[ $? -ne 0 ]]
}

function file_exists {
  [[ -s $1 ]] || [[ -d $1 ]]
}

function not_file_exists {
  [[ ! -s $1 ]] && [[ ! -d $1 ]]
}

function ask_yes_or_no {
    read -p "$1 ... [Y]es or [N]o: "
    case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        y|yes) echo "yes" ;;
        *)     echo "no" ;;
    esac
}

function press_key_to_continue {
  read -p "Press any key to continue when this step is finished" -n 1
}

function doing {
    echo -e "\n\n${background_green}${bold_black} ==> $1 ${reset}"
}

function line {
    echo -e "$1"
}

function pman() { man -t "$@" | open -f -a "Preview" ;}

# prints the path of the front Finder window. Desktop if no window open
function pwdf () {
    osascript <<EOS
        tell application "Finder"
            if (count of Finder windows) is 0 then
                set dir to (desktop as alias)
            else
                set dir to ((target of Finder window 1) as alias)
            end if
            return POSIX path of dir
        end tell
EOS
}

# changes directory to frontmost Finder window
alias cdf='pwdf; cd "$(pwdf)"'

# Remind me of the bash keyboard shortcuts, since I can never remember all of them
function keys () {
    line "Ctrl+a Move cursor to start of line"
    line "Ctrl+e Move cursor to end of line"
    line "Ctrl+b Move back one character"
    line "Alt+b Move back one word"
    line "Ctrl+f Move forward one character"
    line "Alt+f Move forward one word"
    line "Ctrl+d Delete current character"
    line "Ctrl+w Cut the last word"
    line "Ctrl+k Cut everything after the cursor"
    line "Alt+d Cut word after the cursor"
    line "Alt+w Cut word before the cursor"
    line "Ctrl+y Paste the last deleted command"
    line "Ctrl+_ Undo"
    line "Ctrl+u Cut everything before the cursor"
    line "Ctrl+xx Toggle between first and current position"
    line "Ctrl+l Clear the terminal"
    line "Ctrl+c Cancel the command"
    line "Ctrl+r Search command in history - type the search term"
    line "Ctrl+j End the search at current history entry"
    line "Ctrl+g Cancel the search and restore original line"
    line "Ctrl+n Next command from the History"
    line "Ctrl+p previous command from the History"
}
