#!/usr/bin/env bash

alias artisan='php artisan'
alias art='php artisan'
alias migrate="php artisan migrate"
alias fresh="php artisan migrate:fresh --seed"
alias tinker='php artisan tinker'
alias tink='php artisan tinker'

alias phpunit='vendor/bin/phpunit'
alias pu='vendor/bin/phpunit'

alias routes='displayroutes'

alias envoy='envoy run deploy'
alias envoyc='envoy run deploy-only-code'

function displayroutes ()
{
    if [ $# -eq 0 ]; then
        php artisan route:list
    else
        php artisan route:list | grep ${1}
    fi
}
