#!/usr/bin/env bash

#
# Install Brew Cask Apps
#

doing "Installing Apps..."

cask "dropbox"

cask "1password"
cask "1password-cli"
cask "adobe-creative-cloud" # open '/usr/local/Caskroom/adobe-creative-cloud/latest/Creative Cloud Installer.app'
cask "alfred"
# cask "arduino"
cask "bartender"
# cask "charles"
cask "claude"
cask "clipy"
cask "coconutbattery"; press_key_to_continue "Coconutbattery: Set menubar to display '%t  •  %r%s  •  %p%' [Press any key...]"
cask "dash"
cask "dbngin"
cask "discord"
# cask "divvy"
cask "docker-desktop"
cask "firefox"
# cask "flux"
cask "github"
# cask "gitter"
cask "google-chrome"; press_key_to_continue "Chrome: Remember to remove from starting at login. [Press any key...]"
cask "grandperspective"
cask "herd"
# cask "hyper"
cask "imageoptim"
cask "iterm2"
cask "jiggler"
cask "keepingyouawake"
cask "launchcontrol"
# cask "lazy"
# cask "lingon-x"
# cask "macdown"
cask "notion"
# cask "postico"
cask "postman"
# cask "psequel"
cask "raspberry-pi-imager"
# cask "remarkable"
cask "rocket"
# cask "sip"
cask "slack"
cask "spotify"
# cask "spectacle"
# cask "sublime-text"
cask "tableplus"
cask "tastytrade"
cask "the-unarchiver"
cask "tinkerwell"
cask "transmission" # uTorrent
cask "transmit"
# cask "tunnelblick"
# cask "turbo-boost-switcher"
cask "tuxguitar"
cask "visual-studio-code"
# cask "zeplin"
# cask "whatsapp"
cask "zoom"

# QuickLook Plugins
cask "apparency"
# cask "qlcolorcode"
cask "qlmarkdown"
# cask "quicklook-csv"
# cask "quicklook-json"
# cask "qlimagesize"
cask "qlvideo"
# cask "qlstephen"
xattr -d -r com.apple.quarantine ~/Library/QuickLook
